### PR TITLE
Import moment locales to prevent Android crashes

### PR DESCRIPTION
**Pull request by is343**
Android production builds will crash if you try to pass a moment locale to the component without importing the locales from moment first.

### CODE REVIEW

**Comment by is343** [comment]
@vinodkumar8 please check this out. Thanks!

**Comment by vinodkumar8** [comment]
Is that only change required?

**Comment by is343** [comment]
Yes. I got a working solution from moment/moment#3624

The only real change was to import the all of the locales from moment.

Sorry for this long list of commits. It looks like it pulled all of my commits from when I first forked this. It added all of them when I rebased with this master branch.

**Comment by is343** [comment]
@vinodkumar8 would you like me to make any changes?

**Pull request merged**
